### ISSUE TITLE
Error "Request is immutable" when i try to use the ProxyHttpClient example from the documentation §7.2

### ISSUE THREAD

**Issue by pierre-yves-legendre-cbp** [micronaut-projects/micronaut-servlet#262]
### Expected Behavior

No error and we can mutate the HttpRequest

### Actual Behaviour

When I try to use the ProxyHttpClient example from the §7.2 of your documentation (version 3.2)

i have this error ### UnsupportedOperationException("Request is immutable")

The error come, because, in the filter, the request parameter is a **DefaultHttpRequest** and it's not overload the **mutate** method.

### Steps To Reproduce

1. Create a new project micronaut from IntelliJ
2. Add the exact filter (with ProxyHttpClient) example from the document https://docs.micronaut.io/latest/guide/#proxyClient
3. Launch and call the url with "/proxy/toto"

### Environment Information

Windows : 10
Micronaut : 3.2
openjdk : 1.7
gradle : 7.2

### Version

3.2

**Comment by hunsricker** [comment]
> This is probably because you are using a servlet server right?

But it should also work running on a servlet container, shouldn't it? Using netty the proxy is running out of memory, so netty is no option, due to memory leak(s).

I did not find the issue on the core board. So, is this issue fixed? Or are there any workarounds for it?

**Comment by graemerocher** [comment]
it is fixed in the upcoming Micronaut 4 release

**Comment by hunsricker** [comment]
Using 4.0.0-M5 the error still occurs

2023-07-05T16:49:21,513 [ERROR] [io-executor-thread-1 | io.micronaut.http.server.RouteExecutor ] Unexpected error occurred: Request is immutable

**Comment by timyates** [comment]
Thanks for reporting!

This immutability error is fixed in the official Micronaut 4 release

However, I've discovered a different error which prevents this from working

https://github.com/micronaut-projects/micronaut-servlet/pull/542

I'll close this, and track that error over there
